name: Build LaTeX document
on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Scrape and build LaTeX document
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip && \
          sudo -H pip3 install beautifulsoup4 && \
          python3 build.py
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload LaTeX source to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.tex
          asset_name: bisb_bmi_handbook.tex
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload compiled PDF to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: bisb_bmi_handbook.pdf
          tag: ${{ github.ref }}
          overwrite: true
